{% set name = "ariadne" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ariadne-{{ version }}.tar.gz
  sha256: afc5fd2706380ef114f1020dce74e0a42d27b28c8a8565c28191aaaa1808ea21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - graphql-core >=3.2.0,<3.3
    - python >=3.7
    - starlette >0.17,<1.0
    - typing-extensions >=3.6.0

test:
  imports:
    - ariadne
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ariadnegraphql.org/
  dev_url: https://github.com/mirumee/ariadne
  doc_url: https://ariadnegraphql.org/docs/intro
  summary: Ariadne is a Python library for implementing GraphQL servers.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
